<a href="https://colab.research.google.com/github/vmtang11/ids705_ml_ta/blob/main/session2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# IDS705 Machine Learning: Session 2

## Agenda

### Numpy

- Array vs Matrix
- Shape mismatch error for dot product
- Other useful functions

### Linear Algebra to Code
- Taking matrix representations and turning them into code
- Matrix math
- Example: linear regression (weights and error)

If you need a refresher, here's a bit about linear regression using matrices:
https://www.stat.purdue.edu/~boli/stat512/lectures/topic3.pdf

# Numpy
- resource: https://cs231n.github.io/python-numpy-tutorial/#numpy

In [ ]:
import numpy as np

## Array vs Matrix

- np.array: nD, input as numbers
  - values separated by `comma` and enclosed by `[]` for each dimension <br>(in the order of x-axis (innermost square brackets), y-axis (next square brackets), z-axis (so-on), etc)
- np.matrix: 2D only, input as string
  - values separated by `space` within each row and separated by `;` for different columns

__2D matrix__:


In [ ]:
A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
B = np.matrix('1 2 3; 4 5 6; 7 8 9')
print(f"A is an {type(A)} object:\n{A}")
print(f"B is a {type(B)} object:\n{B}")

A is an <class 'numpy.ndarray'> object:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B is a <class 'numpy.matrix'> object:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


__row vector__:
- np.array: 1D array by default shown as row vector
- np.matrix: __not possible__,  still show as 2D matrix with only 1 row

In [ ]:
c = np.array([1, 2, 3]) # (3, ) != (3, 1)
d = np.matrix('1 2 3') # (1, 3)
print(f"c is a 1D row vector:\n{c}")
print(f"d is a 2D matrix with only 1 row:\n{d}")

c is a 1D row vector:
[1 2 3]
d is a 2D matrix with only 1 row:
[[1 2 3]]


__column vector__:
- np.array: need to increase dimension from `(n, )` to `(n, 1)`
  - both `None` and `np.newaxis` adds additional dimension
  - `[:, None]` or `[:, np.newaxis]` adds behind
  - `[None]` or `[np.newaxis]` adds in front, but can use `.T` to transpose
  - adding outer `[]` also adds new dimension in front

- np.matrix: use `;` as separator

In [ ]:
w = np.array([1, 2, 3])[:, None]
x = np.array([1, 2, 3])[np.newaxis].T
y = np.array([[1, 2, 3]]).T
z = np.matrix('1; 2; 3')
print(f"w = \n{w}")
print(f"x = \n{x}")
print(f"y = \n{y}")
print(f"z = \n{z}")

w = 
[[1]
 [2]
 [3]]
x = 
[[1]
 [2]
 [3]]
y = 
[[1]
 [2]
 [3]]
z = 
[[1]
 [2]
 [3]]


## Shape Mismatch
When calculating the dot product, the dimensions of the 2 arrays/matrices have to match, otherwise there will be shape mismatch error.

In [ ]:
print(f"A is a {A.shape} matrix")
print(f"c is a {c.shape} vector")
print(f"w is a {w.shape} matrix")

A is a (3, 3) matrix
c is a (3,) vector
w is a (3, 1) matrix


In [ ]:
ans1 = A.dot(c)
ans2 = A.dot(w)
print(f"A dot c gives a {ans1.shape} vector = {ans1}")
print(f"A dot w gives a {ans2.shape} matrix = \n{ans2}")

A dot c gives a (3,) vector = [14 32 50]
A dot w gives a (3, 1) matrix = 
[[14]
 [32]
 [50]]


In [ ]:
ans3 = A.dot(c.T) # transposing (3,) is still (3,)
print(f"A dot c.T gives a {ans3.shape} vector = {ans3}")
ans4 = A.dot(w.T) # shape mismatch

A dot c.T gives a (3,) vector = [14 32 50]


ValueError: ignored

## Some useful numpy functions

__array dimension__:
- np.squeeze: removes dimensions of size 1 (reverse of adding new dimension with `None` or `np.newaxis`)
- np.flatten: change any array into 1D
- np.reshape: change to any shape (provided the total number of elements stays the same)

In [ ]:
w_squeeze = w.squeeze()
print(f"w is back to a {w_squeeze.shape} vector = {w_squeeze}")
A_flatten = A.flatten()
print(f"A is now to a {A_flatten.shape} vector = {A_flatten}")

w is back to a (3,) vector = [1 2 3]
A is now to a (9,) vector = [1 2 3 4 5 6 7 8 9]


In [ ]:
M = np.random.randint(0,10,(3,8))
print(f"M is a {M.shape} matrix =\n{M}")
M_reshape = M.reshape(4, 6)
print(f"M is reshaped into a {M_reshape.shape} matrix =\n{M_reshape}")

M is a (3, 8) matrix =
[[0 3 7 3 7 6 1 9]
 [6 4 9 0 5 2 3 4]
 [8 3 1 3 5 6 0 7]]
M is reshaped into a (4, 6) matrix =
[[0 3 7 3 7 6]
 [1 9 6 4 9 0]
 [5 2 3 4 8 3]
 [1 3 5 6 0 7]]


- np.c_: combines 1D column vectors horizontally (with same number of rows)
- np.unique: returns unique elements in an array/matrix
- np.argsort: return indices that would sort the array
- np.argmax: return indices of max value, along axis

In [ ]:
np.c_[c,ans1]

array([[ 1, 14],
       [ 2, 32],
       [ 3, 50]])

In [ ]:
np.unique(M)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
M0 = M[0]
np.argsort(M0)

array([0, 6, 1, 3, 5, 2, 4, 7])

In [ ]:
M0[np.argsort(M0)]

array([0, 1, 3, 3, 6, 7, 7, 9])

In [ ]:
np.argmax(M, axis=0)

array([2, 1, 1, 0, 0, 0, 1, 0])

# Linear Algebra to Code
- Taking matrix representations and turning them into code
- Matrix math

## Example: Linear Regression

### Equation

$\hat{y} = Xw + \epsilon$ <br>
$\hat{y} = \hat{f}(x) = \sum_{i=0}^{p}w_ix_i$ <br>
$\hat{f}(x_n) = w^Tx_n$

where:
- $\hat{y}$ = predicted $y$ values
- $X$ = data
- $w$ = weights
- $\epsilon$ = error
- $p$ = number of predictors

### Weights

To find the weights ($w$): <br>
$w = (X'X)^{-1}X'Y$

### Error

To find the error, we'll use mean squared error: <br>
$
\begin{align}
E(\hat{f}) = \frac{1}{N} \sum_{n=1}^N \left( \hat{f}(x_n) - y_n \right) ^2
\end{align}
$

where:
- $N$ = number of data points
- $\hat{f}(x_n)$ = predicted $y$ value
- $y_n$ = actual $y$ value



## Creating Data

To use this example, let's create some random data. We can do so using numpy random normal. We need data for x (features/predictors) and y (target).

In [ ]:
import numpy as np
import random

# set seed for reproducibility
random.seed(11)

# mean = 0, std = 1
x_train = np.random.normal(0, 1, size = (100,3))

# show first 10 rows as an example
x_train[0:10,:]

array([[-2.60242094,  0.75172246,  0.34385265],
       [ 0.56659061,  0.08106306,  1.6870919 ],
       [-0.22828562,  0.22043614, -0.85424999],
       [-0.435791  ,  0.13191385,  1.60922772],
       [-1.09291525, -1.10679567, -0.84150506],
       [ 0.21466988, -0.81447283, -0.88474572],
       [ 1.51170187,  1.92859283, -1.02362354],
       [-0.78845682, -1.08029696,  0.33111453],
       [ 0.37510378, -0.0590894 , -0.67091843],
       [ 0.84145002, -0.72154762,  0.53874882]])

In [ ]:
# create y with coefficients 2, 3, and 4 and some noise so we know what coefficients to expect for w
noise = np.random.normal(0, 1, 100)
y_train = 2 * x_train[:,0] + 3 * x_train[:,1] + 4 * x_train[:,2] + noise

# print y shape to confirm and first 10 as an example
print(f'y shape: {y_train.shape}')
y_train[:10]

y shape: (100,)


array([-1.62978411,  7.26338816, -3.98767757,  5.7200045 , -9.30061642,
       -3.57190111,  4.67231352, -4.78229333, -1.93831737,  1.53534698])

## Finding Weights

Now that we have some data to work with, let's use the formula below to calculate the weights. Because we made our own data, we know to expect the coefficients $w$ to be 2, 3, and 4.

$w = (X'X)^{-1}X'Y$

Because this has a few parts to it, we can break it down into simpler components. <br>
1. Calculate $X'X$
2. Take the inverse
3. Multiply that by $X'$
4. Multiply that by $Y$

In [ ]:
part1 = np.dot(x_train.T, x_train)
part2 = np.linalg.inv(part1)
part3 = np.dot(part2, x_train.T)
part4 = np.dot(part3, y_train)
part4

array([1.98946147, 3.12150315, 3.82625464])

As expected, our coefficients are about 2, 3, and 4. The reason they're slightly off is because we added some random noise.

## Calculating Error

Now that we have our weights, we can calculate the error, we'll use mean squared error: <br>
$
\begin{align}
E(\hat{f}) = \frac{1}{N} \sum_{n=1}^N \left( \hat{f}(x_n) - y_n \right) ^2
\end{align}
$

where:
- $N$ = number of data points
- $\hat{f}(x_n)$ = predicted $y$ value
- $y_n$ = actual $y$ value

Again, we can break this down into a few parts:
1. `yhat`: Calculate $\hat{f}(x_n)$
2. `diff`: Subtract the true $y$ value ($y_n$) from the predicted $y$ value ($\hat{y}$)
3. `diff2`: Square the difference
4. `ssd`: Sum all the squares
5. `e`: Divide by $N$, the number of data points

In [ ]:
# Part 1: Calculating yhat
# print shape and some examples to make sure it's what you expect
yhat = np.dot(x_train, w)
print(f'yhat shape: {yhat.shape}')
yhat[:10]

yhat shape: (100,)


array([-1.57426391,  8.12473802, -3.21226277,  5.96107045, -8.87223775,
       -5.55306158,  4.71468805, -3.49334642, -2.11073434,  1.67325248])

In [ ]:
# Part 2: yhat - y
diff = yhat - y_train
print(f'diff shape: {diff.shape}')
diff[:10]

diff shape: (100,)


array([ 0.0555202 ,  0.86134986,  0.7754148 ,  0.24106595,  0.42837867,
       -1.98116047,  0.04237453,  1.28894691, -0.17241696,  0.1379055 ])

In [ ]:
# Part 3: Square the differences
diff2 = diff**2
print(f'diff squared shape: {diff2.shape}')
diff2[:10]

diff squared shape: (100,)


array([3.08249254e-03, 7.41923576e-01, 6.01268115e-01, 5.81127943e-02,
       1.83508283e-01, 3.92499680e+00, 1.79560049e-03, 1.66138414e+00,
       2.97276094e-02, 1.90179260e-02])

In [ ]:
# Part 4: Sum all the squared differences
ssd = np.sum(diff2)
print(f'ssd shape: {ssd.shape}')
ssd

ssd shape: ()


80.42841192372006

In [ ]:
# Part 5: Divide by N
e = ssd/y_train.shape
e

array([0.80428412])

It's often easier to deal with math and matrices in parts, especially with longer calculations. It also allows you to look at it piece by piece to debug and isolate mistakes. However, you could also easily combine it into a few steps that still make the process clear:

In [ ]:
# Putting it all together
yhat = np.dot(x_train, w)
ssd = np.sum((yhat - y_train)**2)
e = ssd/y_train.shape
e

array([0.80428412])

That's much easier to debug and look at than this:

In [ ]:
e = np.sum((np.dot(x_train, w) - y_train)**2)/y_train.shape
e

array([0.80428412])

Also, you will almost certainly use `yhat` again in other calculations, so it's generally best to save that as its own variable anyway. 